# Dockerfile.server
FROM node:18

WORKDIR /app

# Copy package.json and package-lock.json from the root directory
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the server code
COPY . .

# Expose port
EXPOSE 5001

# Command to run the server
CMD ["npm", "start"]
