version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    env_file:
      - .env

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  mongo-data:
